Editting custom element
ethib137/liferay-portal pull request #280
Opened 2023-12-12 21:23 UTC by MumenTayyem

2023-12-12 21:55 UTC, MumenTayyem commented
ci:test:sf

2023-12-12 21:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/7264/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7264/jenkins-report.html">here</a>.</b></p>

2023-12-12 21:59 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ad700a7ff309d37e95901d678e16b6e56d2b0f84">ad700a7ff309d37e95901d678e16b6e56d2b0f84</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MumenTayyem/liferay-portal/tree/editting-custom-element">editting-custom-element</a><br/>Branch GIT ID: <a href="https://github.com/MumenTayyem/liferay-portal/commit/f452960987a428fa4eead9091fa214af93c9c265">f452960987a428fa4eead9091fa214af93c9c265</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/7264/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7264/jenkins-report.html">here</a>.</h5><pre>     [exec]   9:1  error  imports must be grouped (expected blank line before: "./pages/TicketApp")  @liferay/group-imports
     [exec]   26:36  error  Curly braces are unnecessary here.  react/jsx-curly-brace-presence
     [exec]   29:36  error  Curly braces are unnecessary here.  react/jsx-curly-brace-presence
     [exec] 
     [exec] /opt/dev/projects/github/liferay-portal/workspaces/liferay-ticket-workspace/client-extensions/liferay-ticket-custom-element/src/pages/TicketsByStatusDashboard.tsx
     [exec]   10:1  error  imports must be grouped (expected blank line before: "../components/StatusColumn")  @liferay/group-imports
     [exec]   15:1  error  imports must be grouped (expected blank line before: "../styles/TicketsByStatusDashboard.css")  @liferay/group-imports
     [exec]   100:4  error  Expected blank line before this statement.  padding-line-between-statements
     [exec]   130:35  error  Props should be sorted alphabetically  react/jsx-sort-props
     [exec] 
     [exec] ��� 19 problems (19 errors, 0 warnings)
     [exec]   19 errors and 0 warnings potentially fixable with the `--fix` option.
     [exec] 
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] &gt; Task :portalWorkspacesYarnCheckFormat FAILED
     [exec] Gradle build finished at 2023-12-12 21:59:00.094.
     [exec] 5 actionable tasks: 4 executed, 1 up-to-date
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':portalWorkspacesYarnCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':portalWorkspacesYarnCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:145)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)</pre></details></html>

2023-12-12 22:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/7264/">test-portal-source-format#7264</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7264/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/ethib137/liferay-portal/pull/280">ethib137#280</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2473654117">[master] ci:test:sf - MumenTayyem &gt; ethib137 - PR#280 - 2023-12-12[13:55:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/28500/">publish-testray-report#28500</a><br/></div></div>

2023-12-12 22:19 UTC, MumenTayyem commented
ci:test:sf

2023-12-12 22:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2279/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2279/jenkins-report.html">here</a>.</b></p>

2023-12-12 22:23 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ad700a7ff309d37e95901d678e16b6e56d2b0f84">ad700a7ff309d37e95901d678e16b6e56d2b0f84</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MumenTayyem/liferay-portal/tree/editting-custom-element">editting-custom-element</a><br/>Branch GIT ID: <a href="https://github.com/MumenTayyem/liferay-portal/commit/e566e47037716c5d7576a7cc6ae6ccd8fcac9365">e566e47037716c5d7576a7cc6ae6ccd8fcac9365</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2279/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2279/jenkins-report.html">here</a>.</h5><pre>     [exec] warning "@liferay/eslint-plugin &gt; @typescript-eslint/eslint-plugin &gt; @typescript-eslint/experimental-utils &gt; eslint-utils@3.0.0" has unmet peer dependency "eslint@&gt;=5".
     [exec] warning "@liferay/npm-scripts &gt; @testing-library/react@12.1.5" has incorrect peer dependency "react@&lt;18.0.0".
     [exec] warning "@liferay/npm-scripts &gt; @testing-library/react@12.1.5" has incorrect peer dependency "react-dom@&lt;18.0.0".
     [exec] warning "@liferay/npm-scripts &gt; liferay-lang-key-dev-loader@1.0.3" has incorrect peer dependency "webpack@^3.0.0 || ^4.0.0".
     [exec] warning "@liferay/npm-scripts &gt; script-ext-html-webpack-plugin@2.1.4" has incorrect peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
     [exec] warning "@liferay/npm-scripts &gt; script-ext-html-webpack-plugin@2.1.4" has incorrect peer dependency "html-webpack-plugin@^3.0.0 || ^4.0.0".
     [exec] [4/4] Building fresh packages...
     [exec] Done in 5.24s.
     [exec] 
     [exec] &gt; Task :portalWorkspacesYarnCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts lint &amp;&amp; liferay-npm-scripts format:check
     [exec] 
     [exec] liferay-ticket-workspace/client-extensions/liferay-ticket-custom-element/src/main.tsx: BAD
     [exec] Prettier checked 14 files, 1 file has problems
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':portalWorkspacesYarnCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':portalWorkspacesYarnCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:145)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)</pre></details></html>

2023-12-12 22:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2279/">test-portal-source-format#2279</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2279/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/ethib137/liferay-portal/pull/280">ethib137#280</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2473667539">[master] ci:test:sf - MumenTayyem &gt; ethib137 - PR#280 - 2023-12-12[14:19:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9002/">publish-testray-report#9002</a><br/></div></div>

2023-12-13 08:09 UTC, ethib137 commented
ci:test:sf

2023-12-13 08:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/2331/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2331/jenkins-report.html">here</a>.</b></p>

2023-12-13 08:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3cce38a6b80854f0258b41f37ac8db644878a37e">3cce38a6b80854f0258b41f37ac8db644878a37e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MumenTayyem/liferay-portal/tree/editting-custom-element">editting-custom-element</a><br/>Branch GIT ID: <a href="https://github.com/MumenTayyem/liferay-portal/commit/dafcb78f13f5c22860e538139789dbd01fce8b1e">dafcb78f13f5c22860e538139789dbd01fce8b1e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2331/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2331/jenkins-report.html">here</a>.</h5></details></html>

2023-12-13 08:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2331/">test-portal-source-format#2331</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2331/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/ethib137/liferay-portal/pull/280">ethib137#280</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2473897794">[master] ci:test:sf - MumenTayyem &gt; ethib137 - PR#280 - 2023-12-13[00:09:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/9882/">publish-testray-report#9882</a><br/></div></div>

2023-12-13 12:12 UTC, closed without merging

2023-12-13 12:51 UTC, ethib137 requested changes
Can you add these changes to your new PR? I'll finish reviewing the new PR.

2023-12-13 13:33 UTC, MumenTayyem commented on workspaces/liferay-ticket-workspace/client-extensions/liferay-ticket-custom-element/src/components/TicketPreview.tsx
> +};
Hey @ethib137, these users are created using the batch framework, unfortunately, users images are not supported yet.. so I had to add the images into the assets folder inside the custom element and map them based on the user ERC.

2023-12-13 13:34 UTC, MumenTayyem commented on workspaces/liferay-ticket-workspace/client-extensions/liferay-ticket-custom-element/src/components/StatusColumn.tsx
> +				status.relatedTickets.map((t: any) => (
Yes, I'll fix this.

2023-12-13 13:47 UTC, MumenTayyem commented on workspaces/liferay-ticket-workspace/client-extensions/liferay-ticket-custom-element/src/components/StatusColumn.tsx
> +			key={status.key + '_droppable'}
Yes, correct.

2023-12-13 13:50 UTC, MumenTayyem commented on workspaces/liferay-ticket-workspace/client-extensions/liferay-ticket-custom-element/src/components/StatusColumn.tsx
> +			<h6>{status.name}</h6>
I changed it to the paragraph tag