Dialect Hotkeys
ethib137/liferay-portal pull request #7
Opened 2022-02-09 14:09 UTC by eduardobbgf

2022-02-10 11:53 UTC, ethib137 requested changes
Great work! I'm really happy with how much you all have accomplished with this.

We will go over all the comments on the call today so you both can have a chance to ask questions about my suggestions. 

- The hotkeys frontend token set should probably be broken into 2 separate ones: `hotkeys` and `general`. 
- Any time we run a command to generate code, such as buildLang, we should include the generated code in it's own commit. This makes it easy to update the non generated code and then regenerate the generated code and merge commits. 

Again, I'm really happy with how much you both have learned. Good job.

2022-02-10 11:53 UTC, ethib137 commented on modules/apps/product-navigation/product-navigation-applications-menu-web/src/main/resources/META-INF/resources/js/ApplicationsMenu.js
> +		<kbd className="c-kbd">
This file should not have been changed.

2022-02-10 11:53 UTC, ethib137 commented on modules/apps/frontend-theme/frontend-theme-dialect/src/WEB-INF/frontend-token-definition.json
>  							"name": "hotkeysLgLineHeight",
Following the pattern in other components like Buttons, the individual token should be in the singular form. ie: hotkeyLgLineHeight

2022-02-10 13:04 UTC, ilzamcmed commented
Just starting reviewing :)

2022-02-11 13:33 UTC, ilzamcmed commented
Just starting reviewing :)

2022-05-26 10:14 UTC, closed without merging